server:
  port: 9090
  servlet:
    context-path: /library

spring:
  application:
    name: library
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/books

application:
  weather:
    api-key: 594863a959844e10b64182226210812
    base-url: https://api.weatherapi.com/v1