version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest
#   command: --smallfiles --rest --auth

volumes:
  mongodata: